//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skypeRobotController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magabot didn\'t hear you... \\nIt isn\'t connected yet.")]
        public string failedToSendMessage {
            get {
                return ((string)(this["failedToSendMessage"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6969")]
        public int port {
            get {
                return ((int)(this["port"]));
            }
            set {
                this["port"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hello!  \r\nPlease wait until we give you the control of the robot.")]
        public string welcomeMessage {
            get {
                return ((string)(this["welcomeMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You\'re not controlling Magabot yet. \r\nWait for you turn...")]
        public string waitMessage {
            get {
                return ((string)(this["waitMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hurray!!! \r\nMagabot is now under your command. \r\nRemember: \r\n- \'1\' to Assisted Na" +
            "vigation    \r\n  - \'w\' to go forward \r\n  - \'s\' to go backward\r\n  - \'a\' to go left" +
            "\r\n  - \'d\' to go right\r\n  - \'p\' to stop\r\n- \'2\' to Obstacle Avoidance\r\n- \'3\' to Li" +
            "ne Following")]
        public string controllerMessage {
            get {
                return ((string)(this["controllerMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Hello, \r\nYou\'ve been selected as my admin\"")]
        public string adminMessage {
            get {
                return ((string)(this["adminMessage"]));
            }
        }
    }
}
